FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# wichtig für japan tokenizer
RUN pip install fugashi unidic-lite

COPY . .

CMD ["python", "-m", "src.models.train_model_ice_mk"]