ICE_CONFIG:
  batch_size: 128
  db_train: train
  encoder_lr: 2.0e-05
  es_patience: 3
  learning_rate: 0.003
  max_epochs: 1
  max_len: 128
  predict_split: val
  text_model_id: cl-tohoku/bert-base-japanese-v3
  train_threshold: 0.5
  unfreeze_layers: 2
  val_ratio: 0.1
  val_threshold: 0.5
  vision_model_id: openai/clip-vit-base-patch16
